name: NPM Publish

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - run: cd packages/canvas-trading
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install
      - uses: JS-DevTools/npm-publish@v1
        with:
          package: ./packages/canvas-trading/package.json
          token: ${{ secrets.NPM_TOKEN }}
